version: '3'

volumes:
  pg_data:
  static:
  media:
  static_backend:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_backend:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/app/staticfiles/

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_backend:/etc/nginx/html/static/
      - static:/static/
      - media:/etc/nginx/html/media/
